version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:5.0.6
    env_file: ./mongo_db/mongo.env
    ports:
      - '27017:27017'
    networks:
      - backend-network

  backend:
    container_name: app
    image: node:14
    env_file: .env/development.env
    restart: unless-stopped
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start
    networks:
      - backend-network
    depends_on:
      - mongo 

networks:
  backend-network:

volumes:
  mongo: